version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=your_long_random_secret_string
      - JWT_EXPIRES_IN=7d
      - DATABASE_URL=postgres://postgres:postgres@db:5432/virtual_tour_db
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - backend

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=virtual_tour_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: